name: randu
description: "Randu is a Point Of Sales App fot Staff"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.2.4+31

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  app_settings: 5.1.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.6
  custom_pin_screen: ^1.0.1
  dio: ^5.5.0+1
  #  drago_pos_printer: ^1.0.0
  dotted_border: ^2.1.0
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  esc_pos_utils_plus: ^2.0.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.3
#  location:
#    git:
#      url: https://github.com/Juggler98/flutterlocation
#      path: packages/location
#      ref: 1cc9cae16b9a58de74ffaf8113cb86e247d25739
  go_router: ^14.2.0
  google_fonts: ^6.2.0
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  image: ^4.3.0
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.1.2
  oktoast: ^3.4.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.3.1
  print_bluetooth_thermal: ^1.1.0
  riverpod_annotation: ^2.3.5
  #  shared_preferences: ^2.2.3
  #  thermal_printer: ^1.0.5
  timeago: ^3.7.0
  url_launcher: ^6.3.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^17.2.2
  firebase_core: ^3.6.0
  pretty_qr_code: ^3.3.0
  flutter_timer_countdown: ^1.0.7
  simple_barcode_scanner: ^0.3.0
  just_audio: ^0.9.42
  location: ^6.0.2
  http: ^1.3.0
  get: ^4.1.4

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.7.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  hive_ce_generator: ^1.8.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottiefiles/
    - assets/audio/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CourierNew
      fonts:
        - asset: assets/fonts/courir_new.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/randu-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/randu-logo.png"
    background_color: "#ffffff"
    theme_color: "#FFA500"
  windows:
    generate: true
    image_path: "assets/images/randu-logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/randu-logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash-logo.png
  color_dark: "#ffffff"
  #background_image_dark: "assets/dark-background.png"
  image_dark: assets/images/splash-logo.png
  #branding_dark: assets/dart_dark.png
  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/images/splash-android12.png

    # Splash screen background color.
    color: "#ffffff"

    # App icon background color.
    icon_background_color: "#ffffff"
