// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-lKg2ytm3pSmdkfvm_E7N8OAjE053U0s',
    appId: '1:494170735042:web:0a5b5be6f710782686165b',
    messagingSenderId: '494170735042',
    projectId: 'randu-app',
    authDomain: 'randu-app.firebaseapp.com',
    storageBucket: 'randu-app.appspot.com',
    measurementId: 'G-0P2ZRMPDPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOmOXPWcU1rpjoBR4EFESBNB3i1OggcJk',
    appId: '1:494170735042:android:d36987173846d71e86165b',
    messagingSenderId: '494170735042',
    projectId: 'randu-app',
    storageBucket: 'randu-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrtAIW35AmnaVlhWsd12auSgOCe08JxmM',
    appId: '1:494170735042:ios:6eacd908f46652d586165b',
    messagingSenderId: '494170735042',
    projectId: 'randu-app',
    storageBucket: 'randu-app.appspot.com',
    iosBundleId: 'com.randu.pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrtAIW35AmnaVlhWsd12auSgOCe08JxmM',
    appId: '1:494170735042:ios:ed9b112b6a059a1786165b',
    messagingSenderId: '494170735042',
    projectId: 'randu-app',
    storageBucket: 'randu-app.appspot.com',
    iosBundleId: 'com.randu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-lKg2ytm3pSmdkfvm_E7N8OAjE053U0s',
    appId: '1:494170735042:web:82c8be177408ca6086165b',
    messagingSenderId: '494170735042',
    projectId: 'randu-app',
    authDomain: 'randu-app.firebaseapp.com',
    storageBucket: 'randu-app.appspot.com',
    measurementId: 'G-0MZVJ9RG6N',
  );

}