// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:randu/domain/entities/customer/customer_model.dart';
import 'package:randu/domain/entities/printer/paper_size.dart';
import 'package:randu/domain/entities/printer/printer_folder/printer_folder.dart';
import 'package:randu/domain/entities/printer/printer_model/printer_model.dart';
import 'package:randu/domain/entities/transaction/cart/category_model.dart';
import 'package:randu/domain/entities/transaction/cart/discount_model.dart';
import 'package:randu/domain/entities/transaction/cart/payment/payment_response_data.dart';
import 'package:randu/domain/entities/transaction/cart/payment_method/payment_method_model.dart';
import 'package:randu/domain/entities/transaction/cart/product_model.dart';
import 'package:randu/domain/entities/transaction/cart/request/payment/payment_request_model.dart';
import 'package:randu/domain/entities/transaction/cart/table_model.dart';
import 'package:randu/domain/entities/user_model.dart';
import 'package:randu/presentation/providers/main/cart/cart_provider.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BankModelAdapter());
    registerAdapter(CartItemAdapter());
    registerAdapter(CartStateAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(CustomerModelAdapter());
    registerAdapter(DiscountModelAdapter());
    registerAdapter(FlagModelAdapter());
    registerAdapter(MlSettingUserModelAdapter());
    registerAdapter(PaperSizeModelAdapter());
    registerAdapter(PaymentMethodModelAdapter());
    registerAdapter(PaymentRequestModelAdapter());
    registerAdapter(PaymentResponseDataAdapter());
    registerAdapter(PrinterFolderAdapter());
    registerAdapter(PrinterModelAdapter());
    registerAdapter(ProductModelAdapter());
    registerAdapter(SavedCartInfoAdapter());
    registerAdapter(TableModelAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(VariantModelAdapter());
  }
}
